### PR TITLE
feat: support ros2numpy > 0.0.4

### PR DESCRIPTION
**Pull request by ralwing**
## Description
Supporting current version of [ros2_numpy](https://github.com/Box-Robotics/ros2_numpy/tree/v2.0.11) package, instead of [old](https://github.com/nitesh-subedi/ros2_numpy/tree/c34b9e38bd6fb8fccb1f2725cb4e6a1fd5a39846)

This change allows also to work with both the [driving log replayer](https://github.com/tier4/driving_log_replayer/blob/develop/docs/quick_start/installation.en.md#how-to-build) and t4_perception_dataset

### CODE REVIEW

**Comment by miursh** [comment]
@ralwing 
Thank you for your contribution!
Could you please update the poetry file to install the new ros2_numpy?

**Comment by ralwing** [comment]
> Could you please update the poetry file to install the new ros2_numpy? 

Unfortunately, there's no new version of this package in pip repo, so I'm using the `Box-robotics` repo to install it.  If that's an option, I can add it to the [build_depends.repos](https://github.com/tier4/tier4_perception_dataset/blob/main/build_depends.repos) and remove it from the poetry requirements.

**Comment by miursh** [comment]
@ralwing 
Sorry for the delayed response.

Instead of adding it to build_depends, would it be possible to use [this PR](https://github.com/Box-Robotics/ros2_numpy/pull/11) (after merged) or just use [the PR original branch](https://github.com/mbpeterson70/ros2_numpy/tree/humble) ? 
By using above PR, we can use  `poetry add git+ssh://git@github.com:mbpeterson70/ros2_numpy.git#humble` to add newer ros2_numpy.

**Comment by ralwing** [comment]
Closing this PR, since I don't have time to work on this.

**Comment by ralwing** [comment]
Closing

**Pull request closed without merging**
