### PR TITLE
feat(annotated_to_deepen): add default attributes

### PR DESCRIPTION
**Pull request by kminoda**
## Description

I would like to add a default attributes for annotated_t4_to_deepen, since Deepen requires the attributes to be added to the objects.

## How to review

Create Annotated T4 dataset from rosbag, and please confirm that the attributes in T4 dataset is properly added.

## Reference

None

## Notes for reviewer

None

### CODE REVIEW

**Review by miursh — APPROVED** [review]
Have you confirmed that our annotation pipeline is functioning properly with these changes?

**Comment by kminoda** [comment]
@miursh Yes, I have processed a raw rosbag into deepen format, upload it, and confirmed that we can load the data as well as the pseudo label based annotation JSON without any error.
(BTW I just found out that the test is failing so let me fix that as well)

**Comment by kminoda** [comment]
Since the default attributes will no longer be a mere empty list with this PR, I modified the test script as well: https://github.com/tier4/tier4_perception_dataset/pull/67/commits/4bda3ff67a89cfef8ca9de0a115ad1dbe6965897.
Glad if you could briefly check this as well :pray:

**Comment by miursh** [comment]
I added another change to pass the tests. https://github.com/tier4/tier4_perception_dataset/pull/67/commits/1482737c118781080354cb0c2099854fae06a94b

**Pull request merged**
