### PR TITLE
fix(utils): add cast for intensity

### PR DESCRIPTION
**Pull request by kminoda**
## Description
As we are having a transition in PointCloud Type from XYZI to XYZIRC, intensity field can have both int and float. It is safer to explicitly cast intensity value to avoid unintended behavior.

Confirmed that the intensity is properly converted e.g. from `9919` to `9919.` (float)

Note that this PR won't change the performance of `pointcloud_msg_to_numpy` as the `points_arr` type is converted to `np.float32` anyway. This PR is just to make sure that the conversion happens right after the intensity is declared.

- https://star4.slack.com/archives/C057U9P1HT6/p1720663468462229?thread_ts=1720648594.477359&cid=C057U9P1HT6

## How to review
Please check that the CI passes.

## Reference
- https://star4.slack.com/archives/C057U9P1HT6/p1720663468462229?thread_ts=1720648594.477359&cid=C057U9P1HT6

## Notes for reviewer
None

### CODE REVIEW

**Comment by knzo25** [comment]
@kminoda 
When I did made a clean install I encountered the following:
 - Lock compains that is outdated
 - Auto msgs don't exist anymore which causes issues -> should be deleted?
 - Probably due to the lock had to install dependencies manually
 - Tests have errors (unrelated to this PR, but should they be fixed?)
 
 `88 passed, 11 warnings, 78 errors in 3.94s `

**Comment by kminoda** [comment]
@knzo25 Thank you for the review. Can you post the error of the test? At least on the CI it is OK

**Comment by knzo25** [comment]
@kminoda 
This time the repository setup could be done without issues. However, the tests still fail.
Since it was a (successful) clean installation it was simple to understand why the local and CI/CD behavior differed.

https://github.com/tier4/tier4_perception_dataset
vs.
https://github.com/tier4/tier4_perception_dataset/blob/main/.github/workflows/build-and-test.yaml

The packages being built in the CI/CD are different `autoware_auto_perception_msgs autoware_perception_msgs tier4_perception_msgs` -> just need to update the installation instructions I think

**Comment by knzo25** [comment]
@kminoda 
To test that the values are correct I instrumented the code a little:

```python
    # Convert the PointCloud2 message to a numpy structured array
    points = rnp.point_cloud2.point_cloud2_to_array(pointcloud_msg)
    print(f"points msg fields", pointcloud_msg.fields, flush=True)

    # Extract the x, y, z coordinates and additional fields if available
    xyz = points["xyz"]
    if "intensity" in points.keys():
        print(f"intensity type", points["intensity"].dtype, flush=True)
        #intensity = points["intensity"].astype(np.float32)
        intensity = points["intensity"].astype(np.float32)
        points_arr = np.hstack((xyz, intensity))
        print(f"points_arr type", points_arr.dtype, flush=True)
        print(f"intensity min", np.min(intensity), flush=True)
        print(f"intensity max", np.max(intensity), flush=True)
    else:
        points_arr = xyz
```

Then, I run: `poetry run pytest tests/rosbag2/test_rosbag2_converter.py -s`

To my surprise these are the results:
```python
intensity type uint16
points_arr type float32
intensity min 60.0
intensity max 65475.0
```

This problem is independent of the current PR. I recommend not blindly believe in the CI/CD and check manually the code from time to time.

I had talked with @Shin-kyoto, but the `ros2_numpy` from pip is quite old (and bad !)
For example:
 - They say intensity IS a float32 (https://github.com/nitesh-subedi/ros2_numpy/tree/humble)
 - The code treats it as a uint16 (Ouster?) (https://github.com/nitesh-subedi/ros2_numpy/blob/c34b9e38bd6fb8fccb1f2725cb4e6a1fd5a39846/ros2_numpy/point_cloud2.py#L40)


The ros package version is general in its decoding: https://github.com/Box-Robotics/ros2_numpy/blob/jazzy/ros2_numpy/point_cloud2.py
This is the one that is used in other tier4 repositories

**Comment by knzo25** [comment]
@kminoda

**Comment by kminoda** [comment]
@knzo25 Sorry for the late reply, and thank you for the investigation.

I think the issue you've encountered is now fixed: https://github.com/tier4/tier4_perception_dataset/pull/137

**Comment by knzo25** [comment]
@kminoda 
I see. Just need to be careful with the implicit reinterpret done by `view` in `numpy`, as it could change in the future.

Regarding,
> @kminoda
This time the repository setup could be done without issues. However, the tests still fail.
Since it was a (successful) clean installation it was simple to understand why the local and CI/CD behavior differed.

>https://github.com/tier4/tier4_perception_dataset
vs.
https://github.com/tier4/tier4_perception_dataset/blob/main/.github/workflows/build-and-test.yaml

>The packages being built in the CI/CD are different autoware_auto_perception_msgs autoware_perception_msgs tier4_perception_msgs -> just need to update the installation instructions I think

I will just send a PR afterwards if it is still needed

**Review by knzo25 — APPROVED** [review]
LGTM

**Pull request merged**
