### PR TITLE
docs: add automatic_annotation information

### PR DESCRIPTION
**Pull request by miursh**
This pull request includes updates to the `docs/t4_format_3d_detailed.md` file, adding a new field to the annotation format documentation to indicate whether annotations were made automatically. 

Documentation updates:

* Added the `automatic_annotation` field to indicate if the annotation is done by an automatic annotation tool. [[1]](diffhunk://#diff-d037e39214e5805928db3b4c5c2bfe9768110a1bdd6a29b0f2bbd1479031a889R475) [[2]](diffhunk://#diff-d037e39214e5805928db3b4c5c2bfe9768110a1bdd6a29b0f2bbd1479031a889R635) [[3]](diffhunk://#diff-d037e39214e5805928db3b4c5c2bfe9768110a1bdd6a29b0f2bbd1479031a889R649)

### CODE REVIEW

**Review by Shin-kyoto — COMMENTED** [review]
[Question]

@miursh 
I have some questions about the design:

- Q1. When using an auto-labeling tool integrated with Deepen, is `automatic_annotation` set to true?
- Q2. If auto-labeling is initially added and then corrected manually, is `automatic_annotation` still true?
- Q3. Is it correct to understand that the design philosophy is "if auto-labeling was involved at all, `automatic_annotation` is set to true"?

**Comment by miursh** [comment]
@Shin-kyoto 
> Q1. When using an auto-labeling tool integrated with Deepen, is automatic_annotation set to true?
Do you mean the interpolation function? if so, it depends but in my opinion, it should be true.
> Q2. If auto-labeling is initially added and then corrected manually, is automatic_annotation still true?
No. Once anyone fixed the annotation, this should be false
> Q3. Is it correct to understand that the design philosophy is "if auto-labeling was involved at all, automatic_annotation is set to true"?
Maybe no. 
Automatic_annotation should be true only if no one has edited, fixed, or manually labeled the annotation.
In other words, whether automatic_annotation is set to true or false depends on if the label was fully automated and untouched by any human.

**Comment by ktro2828** [comment]
@miursh Thank you for your PR.
I have some minor questions:
1. Could you share the usage of this field if you can?
2. For `object_ann`, its bbox and mask are annotated automatically first, **but only bbox edited by human**. Is it OK to set `automatic_annotation=False`.

**Comment by miursh** [comment]
@ktro2828 
1. The main usage of this field is for the distinction of pseudo-labeling (using the output of a foundation model as a label). For the Co-MLOps dataset, all data is initially labeled by the foundation model, and then only some selected data is manually labeled.
2. If any label is modified by a human, automatic_annotation should be set to false.

**Review by ktro2828 — APPROVED** [review]

**Pull request merged**
