### PR TITLE
chore: delete `t4-devkit`

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

Remove `t4-devkit` from this repository and move to https://github.com/tier4/t4-devkit.

### test command

```bash

```

### CODE REVIEW

**Review by miursh — COMMENTED** [review]
Could you update the document link [here](https://github.com/tier4/tier4_perception_dataset/blob/main/README.md#usage-of-t4-format-dataset)?

**Comment by ktro2828** [comment]
> Could you update the document link [here](https://github.com/tier4/tier4_perception_dataset/blob/main/README.md#usage-of-t4-format-dataset)?

@miursh Thank you for your review, I updated the link of the document!

**Review by Shin-kyoto — APPROVED** [review]
LGTM

**Review by miursh — APPROVED** [review]

**Comment by ktro2828** [comment]
[NOTE] I will merge this PR once it is confirmed that there is no impact on other repositories.

**Comment by ktro2828** [comment]
@kminoda As mentioned [here](https://star4.slack.com/archives/C077WH3UHK5/p1729151541807569?thread_ts=1724821477.072879&cid=C077WH3UHK5), could you release a new tag after this PR has been merged?

**Pull request merged**
