### PR TITLE
feat: add `tier4-devkit` library

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

Add new package named `t4-devkit` inspired by `nuscenes-devkit`.
`Tier4` API allows us to load and operate t4 custom fields extended from NuScenes schema.

### Sample usage

```python
>>> from t4_devkit import Tier4

# initialization
>>> t4 = Tier4("annotation", "data/tier4")
======
Loading T4 tables in `annotation`...
Reverse indexing...
Done reverse indexing in 0.006 seconds.
======
8 category
13 attribute
4 visibility
106 instance
7 sensor
7 calibrated_sensor
2524 ego_pose
1 log
1 scene
72 sample
2524 sample_data
2390 sample_annotation
1 map
1326 object_ann
0 surface_ann
0 keypoint
Done loading in 0.044 seconds.
======

# visualization

# Rendering scene
## scene_token: str = ... (e.g. t4.scene[0].token)
>>> t4.render_scene(scene_token)

# Rendering instance
## instance_token: str = ... (e.g. t4.instance[0].token)
>>> t4.render_instance(instance_token)

# Rendering pointcloud
## scene_token: str = ...
## If you want ignore distortion parameters, please specify `ignore_distortion=True`
>>> t4.render_pointcloud(scene_token)
```

https://github.com/tier4/tier4_perception_dataset/assets/60615504/f6b710e5-3452-4364-bbce-f473b388d2d1

### Status

- [ ] Publish to `pypi`
- [x] Load annotation files
- [x] Load 3D bboxes
- [x] Load 2D bboxes
- [x] Rendering methods
  - [x] 3D/2D annotations
  - [x] scene/instance
  - [x] pointcloud on images
- [ ] Evaluation functions
- [x] Documents

Currently, we can create a server for documents on our local host and debug with `mkdocs serve`.
After running it, please access to `http://127.0.0.1:8000/` on your browser.

```shell
$ cd t4-devkit
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  mkdocstrings_handlers: Formatting signatures requires Black to be installed.
INFO    -  Documentation built in 0.34 seconds
INFO    -  [17:12:04] Watching paths for changes: 'docs', 'mkdocs.yaml'
INFO    -  [17:12:04] Serving on http://127.0.0.1:8000/

```

## How to review

I tested with T4 dataset `d20b53bf-8b4e-4040-9d2c-6df22120177a`.

### test command

```bash

```

### CODE REVIEW

**Comment by kminoda** [comment]
:fire:

**Comment by ktro2828** [comment]
@kminoda @scepter914 c,c. @miursh I'd appreciate it if you could give me your feedback about design.

**Review by kminoda — COMMENTED** [review]
LGTM for the design (checked that all the necessary APIs are implemented at least to replare `NuScenes` & `NuImages` in `tier4_perception_dataset`)

Should we also review docs and some other nits as well?


BTW I checked current DBv1.x with this and 63 datasets out of 256 resulted in an error :cry: , e.g. 
- https://console.data-search.tier4.jp/projects/prd_jt/t4datasets/20618aba-a1bb-40a3-9f2a-8bcaec11746c
- https://console.data-search.tier4.jp/projects/prd_jt/t4datasets/a7256890-2b60-41eb-ab65-d75cdce9e64d
- https://console.data-search.tier4.jp/projects/prd_jt/t4datasets/3a6bd8e5-1c25-497f-adb2-dd0976dbd6c2
(no errors in DBv1.1)

**Comment by ktro2828** [comment]
@kminoda Thanks for your review and trying it out.
I've updated README, so if you are OK I would merge this PR and move on to next actions.

**Review by kminoda — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
